# -*- coding: utf-8 -*-
"""Experiment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9Uy0K8YV_yS8TvOTGwFn3h1UGbfzQd2
"""

import pandas as pd

df=pd.read_csv("D:/Project17/Titanic-Dataset - Titanic-Dataset (1).csv")

df.head()

df.shape

df['Embarked']=df['Embarked'].fillna(df['Embarked'].ffill())

df['Embarked'].isna().sum()

df['Gender']=df['Gender'].map({'male':1,'female':0})

df['Embarked']=df['Embarked'].map({'S' :0,'C' :1,'Q' :2})

df.info()

X=df[['Pclass','Gender','SibSp','Parch','Embarked']]

y=df['Survived']

print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.tree import DecisionTreeClassifier

default_model=DecisionTreeClassifier(random_state=42)

default_model.fit(X_train,y_train)

y_pred_default=default_model.predict(X_test)
print(y_pred_default)

from sklearn.metrics import accuracy_score,confusion_matrix

default_acc=accuracy_score(y_pred_default,y_test)
print(default_acc)

cm=confusion_matrix(y_test,y_pred_default)
print(cm)

grid_param={
    'criterion':['gini','entropy'],
    'max_depth':[1,2,5,None],
    'min_samples_split':[1,4,12],
    'min_samples_leaf':[1,2,3]
}

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
grid_search=GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),param_grid=grid_param,cv=5,scoring='accuracy')

from sklearn.model_selection import GridSearchCV

grid_search.fit(X_train,y_train)

print(grid_search.best_score_)

print(grid_search.best_params_)

tuned_model=grid_search.best_estimator_

y_pred_tuned=tuned_model.predict(X_test)
print(y_pred_tuned)

tuned_acc=accuracy_score(y_pred_tuned,y_test)
print(tuned_acc)